### ISSUE TITLE
tables -> extended tables -> 'table big boy' is not responsive

### ISSUE THREAD

**Issue by nzjrs** [creativetimofficial/light-bootstrap-dashboard#19]
Or it is slightly responsive, but very badly so. At small sizes columns are cut-off

**Comment by alexandru-paduraru** [comment]
@nzjrs thank you for using our product. It seems you are using the PRO product, here is the repo for the FREE. To fix that please add this code at the end of light-bootstrap-dashboard.css

```css
@media (min-width: 991px){
    .card .table-responsive{
        overflow: scroll;
        margin: 0;
        padding: 0;
    }
}
@media (min-width: 1200px){
    .card .table-responsive{
        overflow: visible;
    }
}
```

Then everything will work fine. 

Best,
Alex
